// This file defines the components of the connection as functions that have
// to be specified by the dynamic C-lib generated by sympy (or matlab)
//
// Christoffel symbols of the second kind are to be given here, so stuff like
// Γ^a_bc

// We have a rank-2 symmetric symbol with 10 indices in the lower components for
// each value of the upper index
// -> 40 independent symbols

//Components of the connection (christoffel symbols)
double G000(const double coords[4]);
double G100(const double coords[4]);
double G200(const double coords[4]);
double G300(const double coords[4]);

double G011(const double coords[4]);
double G111(const double coords[4]);
double G211(const double coords[4]);
double G311(const double coords[4]);

double G022(const double coords[4]);
double G122(const double coords[4]);
double G222(const double coords[4]);
double G322(const double coords[4]);

double G033(const double coords[4]);
double G133(const double coords[4]);
double G233(const double coords[4]);
double G333(const double coords[4]);

//Non-diagonal components
double G001(const double coords[4]);
double G101(const double coords[4]);
double G201(const double coords[4]);
double G301(const double coords[4]);

double G002(const double coords[4]);
double G102(const double coords[4]);
double G202(const double coords[4]);
double G302(const double coords[4]);

double G003(const double coords[4]);
double G103(const double coords[4]);
double G203(const double coords[4]);
double G303(const double coords[4]);

double G012(const double coords[4]);
double G112(const double coords[4]);
double G212(const double coords[4]);
double G312(const double coords[4]);

double G013(const double coords[4]);
double G113(const double coords[4]);
double G213(const double coords[4]);
double G313(const double coords[4]);

double G023(const double coords[4]);
double G123(const double coords[4]);
double G223(const double coords[4]);
double G323(const double coords[4]);