//This file defines the components of the Riemann tensor as functions that have
//to be specified by the dynamic C-lib generated by sympy (or matlab)
//
//All lower indices for the Riemann tensor are followed here (not natural indices):
//R_abcd

//We have a rank-4 tensor that is anti-symmetric in the first two and last two
//components, and symmetric under exchange of these two pairs. That leaves 21
//independent components. In addition, we lose one component (in this case R0123)
// due to the geometric bianchi identity Ra[bcd]=0

//Components of the connection (christoffel symbols)

//R01...
double R0101(const double coords[4]);
double R0102(const double coords[4]);
double R0103(const double coords[4]);
double R0112(const double coords[4]);
double R0113(const double coords[4]);
//R0123 = R0213 - R0312

//R02...
//R0201 already defined!
double R0202(const double coords[4]);
double R0203(const double coords[4]);
double R0212(const double coords[4]);
double R0213(const double coords[4]);
double R0223(const double coords[4]);

//R03...
//R0301 already defined!
//R0302 already defined!
double R0303(const double coords[4]);
double R0312(const double coords[4]);
double R0313(const double coords[4]);
double R0323(const double coords[4]);

//R12...
//R1201 already defined
//R1202 already defined
//R1203 already defined
double R1212(const double coords[4]);
double R1213(const double coords[4]);
double R1223(const double coords[4]);

//R13...
//R1301 already defined
//R1302 already defined
//R1303 already defined
//R1312 already defined
double R1313(const double coords[4]);
double R1323(const double coords[4]);

//R23...
//R2301 already defined 
//R2302 already defined
//R2303 already defined
//R2312 already defined
//R2313 already defined
double R2323(const double coords[4]);