// This file defines the components of the metric tensor as functions that have
// to be specified by the dynamic C-lib generated by sympy (or matlab)
//
// The inverse of the metric tensor will be calculated on the rust side

// We have 10 components in total for a rank-2 symmetric tensor

//Components of the metric tensor
double g00(const double coords[4]);
double g11(const double coords[4]);
double g22(const double coords[4]);
double g33(const double coords[4]);
double g01(const double coords[4]);
double g02(const double coords[4]);
double g03(const double coords[4]);
double g12(const double coords[4]);
double g13(const double coords[4]);
double g23(const double coords[4]);